export const assetTypes = [
  'Bank Account',
  'FD',
  'Mutual Fund',
  'Stocks',
  'Gold',
  'Property',
  'Crypto',
  'Other'
];

export const liabilityTypes = [
  'Credit Card',
  'Personal Loan',
  'Home Loan',
  'Auto Loan',
  'Student Loan',
  'Other'
];

export const defaultAsset = {
  name: "",
  type: "Bank Account",
  value: "",
  purchaseDate: "",
  maturityDate: "",
  expectedReturn: "",
  investmentType: "SIP",
  monthlySIP: "",
  totalInvested: "",
  linkedGoal: "",
  source: "",
  isActive: true,
  bankName: "",
  accountType: "Savings",
  interestRate: "",
  compoundingFrequency: "yearly",
  autoRenewal: false,
  isTaxSaver: false,
  fdType: "lumpsum",
  interestPayout: "cumulative",
  fdTenure: "",
  interestReceived: "",
  installmentAmount: "",
  stockName: "",
  units: "",
  buyPrice: "",
  currentPrice: "",
  goldType: "",
  weight: "",
  goldBuyPrice: "",
  goldCurrentPrice: "",
  propertyType: "",
  location: "",
  purchasePrice: "",
  marketValue: "",
  hasLoan: false,
  ownershipPercent: "100",
  rentalIncome: "",
  notes: "",
  cryptoName: "",
  cryptoUnits: "",
  cryptoBuyPrice: "",
  cryptoCurrentPrice: "",
  otherDescription: "",
  localRule: {
    type: "no_rule",
    changeRate: "",
    frequency: "monthly",
  },
};

export const defaultLiability = {
  name: "",
  type: "Credit Card",
  principal: "",
  interestRate: "",
  tenure: "",
  monthlyInstallment: "",
  outstandingAmount: "",
  lender: "",
  nextPaymentDate: "",
  dueDate: "",
  isActive: true,
  notes: "",
  sanctionDate: "",
  disbursementDate: "",
  emiStartDate: "",
  loanMaturityDate: "",
  localRule: {
    type: "no_rule",
    changeRate: "",
    frequency: "monthly",
  },
};